### ISSUE TITLE
Running as GitHub action using 2FA creates issues

### ISSUE THREAD

**Issue by kai-tub** [intuit/auto#1245]
**Describe the bug**

I am still new to this library and I am not 100% sure if this is actually causing the issue.
I am using it in a non-node setting.
Yesterday I could use the following yml for my project without any problems:

```yml
name: Release

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: git fetch --unshallow --tags
      - name: get shipit
        run: |
          curl -vkL -o - https://github.com/intuit/auto/releases/download/v9.35.1/auto-linux.gz | gunzip > ~/auto
          chmod a+x ~/auto
      - name: Create Release
        env:
          # Using my own personal access token to be able to
          # trigger automatic version bump afterwards.
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          ~/auto shipit
```

Today I am getting this error:

```
ℹ  info      Tagging new tag: v1.0.2 => v1.0.3
ℹ  info      Pushing new tag to GitHub
Error: Running command 'git' with args [push, --follow-tags, --set-upstream, ***github.com/kai-tub/github_action_tester_others, master] failed

remote: Permission to kai-tub/github_action_tester_others.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/kai-tub/github_action_tester_others/': The requested URL returned error: 403

    at ChildProcess.child.on (/snapshot/auto/node_modules/@auto-it/core/dist/utils/exec-promise.js:49:31)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)Error
    at Object.execPromise (/snapshot/auto/node_modules/@auto-it/core/dist/utils/exec-promise.js:15:22)
    at apply.auto.hooks.publish.tapPromise (/snapshot/auto/plugins/git-tag/dist/index.js:73:26)
    at Promise (eval at create (/snapshot/auto/node_modules/@auto-it/core/node_modules/tapable/lib/HookCodeFactory.js:74:10), <anonymous>:16:17)
    at new Promise (<anonymous>)
    at Hook.eval [as promise] (eval at create (/snapshot/auto/node_modules/@auto-it/core/node_modules/tapable/lib/HookCodeFactory.js:74:10), <anonymous>:4:8)
    at Hook.PROMISE_DELEGATE [as _promise] (/snapshot/auto/node_modules/@auto-it/core/node_modules/tapable/lib/Hook.js:22:14)
    at Auto.publishFullRelease (/snapshot/auto/node_modules/@auto-it/core/dist/auto.js:992:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

The only thing that has changed from yesterday to today is that I've enabled 2FA.
I am using the Authy app if it makes any difference.

The most confusing part is, however, that everything works if I run it locally. ???

What I've done:
- Created a new `GH_TOKEN`
- Tested with a new repository
- Tested it locally (which works)

**To Reproduce**

From what I can tell, enable 2FA with the Authy app. A GitHub action using a Personal Access Token will not work anymore.

If I can help provide any more information, I am happy to help. :)

**Comment by hipstersmoothie** [comment]
can you try changing this line?

```
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The default token should have enough permission to do this.

For reference I have 2fa enabled on my GitHub account and have gotten `auto` to release though github-actions.

**Comment by hipstersmoothie** [comment]
I'll try to get a minimal auto-gh-actions sample together

**Comment by kai-tub** [comment]
I am getting the same error:

```
ℹ  info      Tagging new tag: v1.0.2 => v1.0.3
ℹ  info      Pushing new tag to GitHub
Error: Running command 'git' with args [push, --follow-tags, --set-upstream, ***github.com/kai-tub/github_action_tester_others, master] failed

remote: Permission to kai-tub/github_action_tester_others.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/kai-tub/github_action_tester_others/': The requested URL returned error: 403

    at ChildProcess.child.on (/snapshot/auto/node_modules/@auto-it/core/dist/utils/exec-promise.js:49:31)
    at ChildProcess.emit (events.js:198:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)Error
    at Object.execPromise (/snapshot/auto/node_modules/@auto-it/core/dist/utils/exec-promise.js:15:22)
    at apply.auto.hooks.publish.tapPromise (/snapshot/auto/plugins/git-tag/dist/index.js:73:26)
    at Promise (eval at create (/snapshot/auto/node_modules/@auto-it/core/node_modules/tapable/lib/HookCodeFactory.js:74:10), <anonymous>:16:17)
    at new Promise (<anonymous>)
    at Hook.eval [as promise] (eval at create (/snapshot/auto/node_modules/@auto-it/core/node_modules/tapable/lib/HookCodeFactory.js:74:10), <anonymous>:4:8)
    at Hook.PROMISE_DELEGATE [as _promise] (/snapshot/auto/node_modules/@auto-it/core/node_modules/tapable/lib/Hook.js:22:14)
    at Auto.publishFullRelease (/snapshot/auto/node_modules/@auto-it/core/dist/auto.js:992:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
##[error]Process completed with exit code 1.
```

**Comment by kai-tub** [comment]
I am noticing more weird errors on GitHub.
Maybe the issue lies on GitHub?
https://www.githubstatus.com/incidents/6tcfpztf6j9m

**Comment by hipstersmoothie** [comment]
Forked you repo and I can't even get it to build https://github.com/hipstersmoothie/github_action_tester_others/actions

**Comment by hipstersmoothie** [comment]
The action doesn't even start so this might be a GitHub issue

**Comment by kai-tub** [comment]
After GitHub released their fixes everything is working now as expected.
I always get the perfect timing for the weirdest bugs... 😅 
Nevertheless, thanks for your, amazingly fast, help. :)
