### ISSUE TITLE
node-fetch resolution dependency issue

### ISSUE THREAD

**Issue by JackHowa** [intuit/auto#1593]
**Is your feature request related to a problem? Please describe.**

- Seeing security dependency issue in storybook deployer around `node-fetch` https://github.com/storybookjs/storybook-deployer/network/alert/yarn.lock/node-fetch/open

**Describe the solution you'd like**

- Would appreciate it if greater than 2.6.1 version is used for node-fetch, possibly using resolution

**Describe alternatives you've considered**

- I don't think there's any alternatives to node-fetch

**Additional context**

- node-fetch top-level dependency is good. However, toolbox-optimizer is awaiting release https://github.com/ampproject/amp-toolbox/pull/921
- I believe cross-fetch could be updated without issue 
- storybook-deployer nonetheless is using an older version of auto, but I wasn't sure it would fix it considering auto is using nested dependencies of node-fetch

storybook deployer dependency: 

```
% yarn why node-fetch
yarn why v1.22.5
[1/4] 🤔  Why do we have the module "node-fetch"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "node-fetch@2.6.0"
info Reasons this module exists
   - "@auto-it#all-contributors#@auto-it#core" depends on it
   - Hoisted from "@auto-it#all-contributors#@auto-it#core#node-fetch"
   - Hoisted from "@auto-it#all-contributors#@auto-it#core#@octokit#rest#@octokit#request#node-fetch"
info Disk size without dependencies: "172KB"
info Disk size with unique dependencies: "172KB"
info Disk size with transitive dependencies: "172KB"
info Number of shared dependencies: 0
✨  Done in 0.24s.
```

```
 auto % yarn list node-fetch
yarn list v1.22.5
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ @ampproject/toolbox-optimizer@2.6.0
│  └─ node-fetch@2.6.0
├─ cross-fetch@3.0.5
│  └─ node-fetch@2.6.0
└─ node-fetch@2.6.1
✨  Done in 1.21s.

**Comment by hipstersmoothie** [comment]
I can take a look at this sometime next week. if you submit a pr i'll release a canary version so you can test the fix

**Comment by hipstersmoothie** [comment]
Not sure this is too fixable until amp-project makes a release. Seem like they could use `auto` 😉

**Comment by JackHowa** [comment]
@hipstersmoothie worked as expected after upgrading. will submit fix

**Comment by JackHowa** [comment]
Run into issues after running `yarn upgrade` with tests. I think it's resolved as far as storybook-deployer concerned: 

```
 FAIL  plugins/twitter/__tests__/twitter.test.ts
  ● Test suite failed to run

    plugins/twitter/__tests__/twitter.test.ts:1:30 - error TS2307: Cannot find module '@auto-it/core' or its corresponding type declarations.

    1 import Auto, { SEMVER } from "@auto-it/core";
                                   ~~~~~~~~~~~~~~~
    plugins/twitter/__tests__/twitter.test.ts:2:27 - error TS2307: Cannot find module '@auto-it/core/dist/utils/make-hooks' or its corresponding type declarations.

    2 import { makeHooks } from "@auto-it/core/dist/utils/make-hooks";
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 FAIL  plugins/brew/__tests__/brew.test.ts
  ● Test suite failed to run

    plugins/brew/__tests__/brew.test.ts:1:18 - error TS2307: Cannot find module '@auto-it/core' or its corresponding type declarations.

    1 import Auto from "@auto-it/core";
                       ~~~~~~~~~~~~~~~
    plugins/brew/__tests__/brew.test.ts:2:27 - error TS2307: Cannot find module '@auto-it/core/dist/utils/make-hooks' or its corresponding type declarations.

    2 import { makeHooks } from "@auto-it/core/dist/utils/make-hooks";
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    plugins/brew/__tests__/brew.test.ts:3:26 - error TS2307: Cannot find module '@auto-it/core/dist/utils/logger' or its corresponding type declarations.

    3 import { dummyLog } from "@auto-it/core/dist/utils/logger";
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 FAIL  plugins/gh-pages/__tests__/gh-pages.test.ts
  ● Test suite failed to run

    plugins/gh-pages/__tests__/gh-pages.test.ts:1:29 - error TS2307: Cannot find module '@auto-it/core' or its corresponding type declarations.

    1 import { execPromise } from "@auto-it/core";
                                  ~~~~~~~~~~~~~~~
    plugins/gh-pages/__tests__/gh-pages.test.ts:3:27 - error TS2307: Cannot find module '@auto-it/core/dist/utils/make-hooks' or its corresponding type declarations.

    3 import { makeHooks } from "@auto-it/core/dist/utils/make-hooks";
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    plugins/gh-pages/__tests__/gh-pages.test.ts:4:26 - error TS2307: Cannot find module '@auto-it/core/dist/utils/logger' or its corresponding type declarations.

    4 import { dummyLog } from "@auto-it/core/dist/utils/logger";
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 FAIL  plugins/jira/__tests__/jira.test.ts
  ● Test suite failed to run

    plugins/jira/__tests__/jira.test.ts:1:30 - error TS2307: Cannot find module '@auto-it/core' or its corresponding type declarations.

    1 import Auto, { SEMVER } from "@auto-it/core";
                                   ~~~~~~~~~~~~~~~
    plugins/jira/__tests__/jira.test.ts:2:31 - error TS2307: Cannot find module '@auto-it/core/dist/__tests__/make-commit-from-msg' or its corresponding type declarations.

    2 import makeCommitFromMsg from "@auto-it/core/dist/__tests__/make-commit-from-msg";
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    plugins/jira/__tests__/jira.test.ts:5:8 - error TS2307: Cannot find module '@auto-it/core/dist/changelog' or its corresponding type declarations.

    5 } from "@auto-it/core/dist/changelog";
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    plugins/jira/__tests__/jira.test.ts:6:22 - error TS2307: Cannot find module '@auto-it/core/dist/log-parse' or its corresponding type declarations.

    6 import LogParse from "@auto-it/core/dist/log-parse";
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    plugins/jira/__tests__/jira.test.ts:7:31 - error TS2307: Cannot find module '@auto-it/core/dist/semver' or its corresponding type declarations.

    7 import { defaultLabels } from "@auto-it/core/dist/semver";
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    plugins/jira/__tests__/jira.test.ts:8:26 - error TS2307: Cannot find module '@auto-it/core/dist/utils/logger' or its corresponding type declarations.

    8 import { dummyLog } from "@auto-it/core/dist/utils/logger";
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    plugins/jira/__tests__/jira.test.ts:12:8 - error TS2307: Cannot find module '@auto-it/core/dist/utils/make-hooks' or its corresponding type declarations.

    12 } from "@auto-it/core/dist/utils/make-hooks";
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 FAIL  plugins/first-time-contributor/__tests__/first-time-contributor.test.ts
  ● Test suite failed to run

    plugins/first-time-contributor/__tests__/first-time-contributor.test.ts:1:23 - error TS2307: Cannot find module '@auto-it/core' or its corresponding type declarations.

    1 import * as Auto from "@auto-it/core";
                            ~~~~~~~~~~~~~~~
    plugins/first-time-contributor/__tests__/first-time-contributor.test.ts:2:31 - error TS2307: Cannot find module '@auto-it/core/dist/__tests__/make-commit-from-msg' or its corresponding type declarations.

    2 import makeCommitFromMsg from "@auto-it/core/dist/__tests__/make-commit-from-msg";
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    plugins/first-time-contributor/__tests__/first-time-contributor.test.ts:3:23 - error TS2307: Cannot find module '@auto-it/core/dist/changelog' or its corresponding type declarations.

    3 import Changelog from "@auto-it/core/dist/changelog";
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    plugins/first-time-contributor/__tests__/first-time-contributor.test.ts:8:8 - error TS2307: Cannot find module '@auto-it/core/dist/utils/make-hooks' or its corresponding type declarations.

    8 } from "@auto-it/core/dist/utils/make-hooks";
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 FAIL  plugins/upload-assets/__tests__/upload-assets.test.ts
  ● Test suite failed to run

    plugins/upload-assets/__tests__/upload-assets.test.ts:1:18 - error TS2307: Cannot find module '@auto-it/core' or its corresponding type declarations.

    1 import Auto from "@auto-it/core";
                       ~~~~~~~~~~~~~~~
    plugins/upload-assets/__tests__/upload-assets.test.ts:2:27 - error TS2307: Cannot find module '@auto-it/core/dist/utils/make-hooks' or its corresponding type declarations.

    2 import { makeHooks } from "@auto-it/core/dist/utils/make-hooks";
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    plugins/upload-assets/__tests__/upload-assets.test.ts:6:26 - error TS2307: Cannot find module '@auto-it/core/dist/utils/logger' or its corresponding type declarations.

    6 import { dummyLog } from "@auto-it/core/dist/utils/logger";
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 FAIL  packages/core/src/__tests__/config.test.ts
  ● Test suite failed to run

    Cannot find module '@auto-it/bot-list' from 'packages/core/src/changelog.ts'

    Require stack:
      packages/core/src/changelog.ts
      packages/core/src/release.ts
      packages/core/src/config.ts
      packages/core/src/__tests__/config.test.ts

      2 | import { URL } from "url";
      3 | import join from "url-join";
    > 4 | import botList from "@auto-it/bot-list";
        | ^
      5 | 
      6 | import { ICommitAuthor, IExtendedCommit } from "./log-parse";
      7 | import SEMVER, { ILabelDefinition } from "./semver";

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (packages/core/src/changelog.ts:4:1)

 FAIL  packages/core/src/utils/__tests__/load-plugin.test.ts
  ● listPlugins › should get plugins from autorc

    expect(received).toMatchSnapshot()

    Snapshot name: `listPlugins should get plugins from autorc 1`

    - Snapshot  - 1
    + Received  + 1

      Array [
        "Found the following plugins in your .autorc:

    - - npm (@auto-it/npm)",
    + - npm ()",
      ]

      164 |     exec.mockReturnValue("");
      165 |     await listPlugins({ plugins: ["npm"] } as any, dummyLog());
    > 166 |     expect(log.mock.calls[0]).toMatchSnapshot();
          |                               ^
      167 |   });
      168 | 
      169 |   test("should get plugins from local module", async () => {

      at Object.<anonymous> (packages/core/src/utils/__tests__/load-plugin.test.ts:166:31)

  ● listPlugins › should get plugins from local module

    expect(received).toMatchSnapshot()

    Snapshot name: `listPlugins should get plugins from local module 1`

    - Snapshot  - 1
    + Received  + 1

      Array [
        "Found the following plugins in your .autorc:

    - - npm (@auto-it/npm)",
    + - npm ()",
      ]

      173 |     );
      174 |     await listPlugins({ plugins: ["npm"] } as any, dummyLog());
    > 175 |     expect(log.mock.calls[0]).toMatchSnapshot();
          |                               ^
      176 |     expect(log.mock.calls[2]).toMatchSnapshot();
      177 |     expect(log.mock.calls[4]).toMatchSnapshot();
      178 |   });

      at Object.<anonymous> (packages/core/src/utils/__tests__/load-plugin.test.ts:175:31)

 FAIL  plugins/s3/__tests__/s3.test.ts
  ● Test suite failed to run

    plugins/s3/__tests__/s3.test.ts:1:18 - error TS2307: Cannot find module '@auto-it/core' or its corresponding type declarations.

    1 import Auto from "@auto-it/core";
                       ~~~~~~~~~~~~~~~
    plugins/s3/__tests__/s3.test.ts:2:26 - error TS2307: Cannot find module '@auto-it/core/dist/utils/logger' or its corresponding type declarations.

    2 import { dummyLog } from "@auto-it/core/dist/utils/logger";
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    plugins/s3/__tests__/s3.test.ts:3:27 - error TS2307: Cannot find module '@auto-it/core/dist/utils/make-hooks' or its corresponding type declarations.

    3 import { makeHooks } from "@auto-it/core/dist/utils/make-hooks";
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 FAIL  plugins/npm/__tests__/set-npm-token.test.ts
  ● Test suite failed to run

    plugins/npm/__tests__/set-npm-token.test.ts:3:26 - error TS2307: Cannot find module '@auto-it/core/dist/utils/logger' or its corresponding type declarations.

    3 import { dummyLog } from "@auto-it/core/dist/utils/logger";
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 FAIL  plugins/git-tag/__tests__/git-tag.test.ts
  ● Test suite failed to run

    plugins/git-tag/__tests__/git-tag.test.ts:1:23 - error TS2307: Cannot find module '@auto-it/core' or its corresponding type declarations.

    1 import * as Auto from "@auto-it/core";
                            ~~~~~~~~~~~~~~~
    plugins/git-tag/__tests__/git-tag.test.ts:2:27 - error TS2307: Cannot find module '@auto-it/core/dist/utils/make-hooks' or its corresponding type declarations.

    2 import { makeHooks } from "@auto-it/core/dist/utils/make-hooks";
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    plugins/git-tag/__tests__/git-tag.test.ts:3:26 - error TS2307: Cannot find module '@auto-it/core/dist/utils/logger' or its corresponding type declarations.

    3 import { dummyLog } from "@auto-it/core/dist/utils/logger";
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 FAIL  packages/core/src/__tests__/remote.test.ts
  ● Test suite failed to run

    Cannot find module '@auto-it/bot-list' from 'packages/core/src/changelog.ts'

    Require stack:
      packages/core/src/changelog.ts
      packages/core/src/release.ts
      packages/core/src/config.ts
      packages/core/src/auto.ts
      packages/core/src/__tests__/remote.test.ts

      2 | import { URL } from "url";
      3 | import join from "url-join";
    > 4 | import botList from "@auto-it/bot-list";
        | ^
      5 | 
      6 | import { ICommitAuthor, IExtendedCommit } from "./log-parse";
      7 | import SEMVER, { ILabelDefinition } from "./semver";

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (packages/core/src/changelog.ts:4:1)

 FAIL  packages/core/src/__tests__/semver.test.ts
  ● Test suite failed to run

    Cannot find module '@auto-it/bot-list' from 'packages/core/src/changelog.ts'

    Require stack:
      packages/core/src/changelog.ts
      packages/core/src/release.ts
      packages/core/src/__tests__/semver.test.ts

      2 | import { URL } from "url";
      3 | import join from "url-join";
    > 4 | import botList from "@auto-it/bot-list";
        | ^
      5 | 
      6 | import { ICommitAuthor, IExtendedCommit } from "./log-parse";
      7 | import SEMVER, { ILabelDefinition } from "./semver";

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (packages/core/src/changelog.ts:4:1)

 FAIL  packages/core/src/__tests__/major-version-branches.test.ts
  ● Test suite failed to run

    Cannot find module '@auto-it/bot-list' from 'packages/core/src/changelog.ts'

    Require stack:
      packages/core/src/changelog.ts
      packages/core/src/release.ts
      packages/core/src/config.ts
      packages/core/src/auto.ts
      packages/core/src/__tests__/major-version-branches.test.ts

      2 | import { URL } from "url";
      3 | import join from "url-join";
    > 4 | import botList from "@auto-it/bot-list";
        | ^
      5 | 
      6 | import { ICommitAuthor, IExtendedCommit } from "./log-parse";
      7 | import SEMVER, { ILabelDefinition } from "./semver";

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (packages/core/src/changelog.ts:4:1)

 FAIL  packages/cli/__tests__/args.test.ts
  ● Test suite failed to run

    packages/cli/src/parse-args.ts:20:8 - error TS2307: Cannot find module '@auto-it/core' or its corresponding type declarations.

    20 } from "@auto-it/core";
              ~~~~~~~~~~~~~~~

 FAIL  plugins/omit-commits/__tests__/omit-commits.test.ts
  ● Test suite failed to run

    plugins/omit-commits/__tests__/omit-commits.test.ts:1:18 - error TS2307: Cannot find module '@auto-it/core' or its corresponding type declarations.

    1 import Auto from "@auto-it/core";
                       ~~~~~~~~~~~~~~~
    plugins/omit-commits/__tests__/omit-commits.test.ts:2:31 - error TS2307: Cannot find module '@auto-it/core/dist/__tests__/make-commit-from-msg' or its corresponding type declarations.

    2 import makeCommitFromMsg from "@auto-it/core/dist/__tests__/make-commit-from-msg";
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    plugins/omit-commits/__tests__/omit-commits.test.ts:3:22 - error TS2307: Cannot find module '@auto-it/core/dist/log-parse' or its corresponding type declarations.

    3 import LogParse from "@auto-it/core/dist/log-parse";
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    plugins/omit-commits/__tests__/omit-commits.test.ts:7:8 - error TS2307: Cannot find module '@auto-it/core/dist/utils/make-hooks' or its corresponding type declarations.

    7 } from "@auto-it/core/dist/utils/make-hooks";
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 FAIL  plugins/omit-release-notes/__tests__/omit-release-notes.test.ts
  ● Test suite failed to run

    plugins/omit-release-notes/__tests__/omit-release-notes.test.ts:1:30 - error TS2307: Cannot find module '@auto-it/core' or its corresponding type declarations.

    1 import Auto, { SEMVER } from "@auto-it/core";
                                   ~~~~~~~~~~~~~~~
    plugins/omit-release-notes/__tests__/omit-release-notes.test.ts:2:31 - error TS2307: Cannot find module '@auto-it/core/dist/__tests__/make-commit-from-msg' or its corresponding type declarations.

    2 import makeCommitFromMsg from "@auto-it/core/dist/__tests__/make-commit-from-msg";
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    plugins/omit-release-notes/__tests__/omit-release-notes.test.ts:3:23 - error TS2307: Cannot find module '@auto-it/core/dist/changelog' or its corresponding type declarations.

    3 import Changelog from "@auto-it/core/dist/changelog";
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    plugins/omit-release-notes/__tests__/omit-release-notes.test.ts:7:8 - error TS2307: Cannot find module '@auto-it/core/dist/utils/make-hooks' or its corresponding type declarations.

    7 } from "@auto-it/core/dist/utils/make-hooks";
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 FAIL  packages/core/src/__tests__/auto-make-changelog.test.ts
  ● Test suite failed to run

    Cannot find module '@auto-it/bot-list' from 'packages/core/src/changelog.ts'

    Require stack:
      packages/core/src/changelog.ts
      packages/core/src/release.ts
      packages/core/src/config.ts
      packages/core/src/auto.ts
      packages/core/src/__tests__/auto-make-changelog.test.ts

      2 | import { URL } from "url";
      3 | import join from "url-join";
    > 4 | import botList from "@auto-it/bot-list";
        | ^
      5 | 
      6 | import { ICommitAuthor, IExtendedCommit } from "./log-parse";
      7 | import SEMVER, { ILabelDefinition } from "./semver";

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (packages/core/src/changelog.ts:4:1)

 FAIL  plugins/microsoft-teams/__tests__/microsoft-teams.test.ts
  ● Test suite failed to run

    plugins/microsoft-teams/__tests__/microsoft-teams.test.ts:2:34 - error TS2307: Cannot find module '@auto-it/slack' or its corresponding type declarations.

    2 import { sanitizeMarkdown } from "@auto-it/slack";
                                       ~~~~~~~~~~~~~~~~

 FAIL  packages/core/src/__tests__/get-remote.test.ts
  ● Test suite failed to run

    Cannot find module '@auto-it/bot-list' from 'packages/core/src/changelog.ts'

    Require stack:
      packages/core/src/changelog.ts
      packages/core/src/release.ts
      packages/core/src/config.ts
      packages/core/src/auto.ts
      packages/core/src/__tests__/get-remote.test.ts

      2 | import { URL } from "url";
      3 | import join from "url-join";
    > 4 | import botList from "@auto-it/bot-list";
        | ^
      5 | 
      6 | import { ICommitAuthor, IExtendedCommit } from "./log-parse";
      7 | import SEMVER, { ILabelDefinition } from "./semver";

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (packages/core/src/changelog.ts:4:1)

 FAIL  plugins/pr-body-labels/__tests__/pr-body-labels.test.ts
  ● Test suite failed to run

    plugins/pr-body-labels/__tests__/pr-body-labels.test.ts:1:27 - error TS2307: Cannot find module '@auto-it/core/dist/utils/make-hooks' or its corresponding type declarations.

    1 import { makeHooks } from "@auto-it/core/dist/utils/make-hooks";
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 FAIL  packages/core/src/__tests__/auto-canary-local.test.ts
  ● Test suite failed to run

    Cannot find module '@auto-it/bot-list' from 'packages/core/src/changelog.ts'

    Require stack:
      packages/core/src/changelog.ts
      packages/core/src/release.ts
      packages/core/src/config.ts
      packages/core/src/auto.ts
      packages/core/src/__tests__/auto-canary-local.test.ts

      2 | import { URL } from "url";
      3 | import join from "url-join";
    > 4 | import botList from "@auto-it/bot-list";
        | ^
      5 | 
      6 | import { ICommitAuthor, IExtendedCommit } from "./log-parse";
      7 | import SEMVER, { ILabelDefinition } from "./semver";

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (packages/core/src/changelog.ts:4:1)

 FAIL  packages/core/src/__tests__/determine-next-version.test.ts
  ● Test suite failed to run

    Cannot find module '@auto-it/bot-list' from 'packages/core/src/changelog.ts'

    Require stack:
      packages/core/src/changelog.ts
      packages/core/src/release.ts
      packages/core/src/config.ts
      packages/core/src/auto.ts
      packages/core/src/__tests__/determine-next-version.test.ts

      2 | import { URL } from "url";
      3 | import join from "url-join";
    > 4 | import botList from "@auto-it/bot-list";
        | ^
      5 | 
      6 | import { ICommitAuthor, IExtendedCommit } from "./log-parse";
      7 | import SEMVER, { ILabelDefinition } from "./semver";

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (packages/core/src/changelog.ts:4:1)

 FAIL  packages/core/src/__tests__/auto-git-user-in-ci.test.ts
  ● Test suite failed to run

    Cannot find module '@auto-it/bot-list' from 'packages/core/src/changelog.ts'

    Require stack:
      packages/core/src/changelog.ts
      packages/core/src/release.ts
      packages/core/src/config.ts
      packages/core/src/auto.ts
      packages/core/src/__tests__/auto-git-user-in-ci.test.ts

      2 | import { URL } from "url";
      3 | import join from "url-join";
    > 4 | import botList from "@auto-it/bot-list";
        | ^
      5 | 
      6 | import { ICommitAuthor, IExtendedCommit } from "./log-parse";
      7 | import SEMVER, { ILabelDefinition } from "./semver";

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (packages/core/src/changelog.ts:4:1)

 FAIL  packages/core/src/__tests__/auto-comment.test.ts
  ● Test suite failed to run

    Cannot find module '@auto-it/bot-list' from 'packages/core/src/changelog.ts'

    Require stack:
      packages/core/src/changelog.ts
      packages/core/src/release.ts
      packages/core/src/config.ts
      packages/core/src/auto.ts
      packages/core/src/__tests__/auto-comment.test.ts

      2 | import { URL } from "url";
      3 | import join from "url-join";
    > 4 | import botList from "@auto-it/bot-list";
        | ^
      5 | 
      6 | import { ICommitAuthor, IExtendedCommit } from "./log-parse";
      7 | import SEMVER, { ILabelDefinition } from "./semver";

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (packages/core/src/changelog.ts:4:1)

 FAIL  packages/cli/__tests__/bundle.test.ts
  ● bundle should function

    Command failed: gunzip -c /Users/jackhowa/sites/auto/packages/cli/binary/auto-macos > /Users/jackhowa/sites/auto/packages/cli/auto
    gunzip: can't stat: /Users/jackhowa/sites/auto/packages/cli/binary/auto-macos (/Users/jackhowa/sites/auto/packages/cli/binary/auto-macos.gz): No such file or directory

      10 |   const binary = path.join(__dirname, "../auto");
      11 | 
    > 12 |   execSync(`gunzip -c ${zip} > ${binary}`);
         |   ^
      13 |   execSync(`chmod +x ${binary}`);
      14 | 
      15 |   expect(

      at Object.<anonymous> (packages/cli/__tests__/bundle.test.ts:12:3)

 FAIL  packages/core/src/__tests__/auto-env.test.ts
  ● Test suite failed to run

    Cannot find module '@auto-it/bot-list' from 'packages/core/src/changelog.ts'

    Require stack:
      packages/core/src/changelog.ts
      packages/core/src/release.ts
      packages/core/src/config.ts
      packages/core/src/auto.ts
      packages/core/src/__tests__/auto-env.test.ts

      2 | import { URL } from "url";
      3 | import join from "url-join";
    > 4 | import botList from "@auto-it/bot-list";
        | ^
      5 | 
      6 | import { ICommitAuthor, IExtendedCommit } from "./log-parse";
      7 | import SEMVER, { ILabelDefinition } from "./semver";

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (packages/core/src/changelog.ts:4:1)

 FAIL  packages/cli/__tests__/main.test.ts
  ● Test suite failed to run

    packages/cli/src/run.ts:21:8 - error TS2307: Cannot find module '@auto-it/core' or its corresponding type declarations.

    21 } from "@auto-it/core";
              ~~~~~~~~~~~~~~~
    packages/cli/src/run.ts:107:9 - error TS2571: Object is of type 'unknown'.

    107         project?.html_url || ""
                ~~~~~~~


Snapshot Summary
 › 2 snapshots failed from 1 test suite. Inspect your code changes or run `yarn test -u` to update them.

Test Suites: 46 failed, 12 passed, 58 total
Tests:       3 failed, 122 passed, 125 total
Snapshots:   2 failed, 22 passed, 24 total
Time:        12.893 s
Ran all test suites.
⚠  warning   Cannot find module '/snapshot/auto/plugins/baz/dist/index.js' from 'packages/core/src/utils/try-require.ts'
⚠  warning   Cannot find module 'auto-plugin-baz' from 'packages/core/src/utils/try-require.ts'
⚠  warning   Cannot find module '@auto-it/baz' from 'packages/core/src/utils/try-require.ts'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
jackhowa@Jacks-Mac-mini auto %
