### ISSUE TITLE
Cannot modify pre-existing version

### ISSUE THREAD

**Issue by tl-NASEEBULLAH-AHMADI** [intuit/auto#2128]
Hi there 👋 I'm getting a "cannot modify pre-existing version" error message when I merge a PR to a pre-release branch. Any idea what it means?

My thinking is because the tag version already exists in my refectory JFrog? If that's the case, how can I fix it or force auto to generate a new tag version?

Also, how does `auto` calculate the new tag version? It is based on the latest commit in commit history?

```
lerna http fetch PUT 403 https://*********.jfrog.io/artifactory/api/npm/npm/@tl-prisma%2ftheme 315ms
lerna sill Error: 403 Forbidden - PUT https://*********.jfrog.io/artifactory/api/npm/npm/@tl-prisma%2ftheme - forbidden
lerna sill     at /home/********/*********-prisma/node_modules/@evocateur/npm-registry-fetch/check-response.js:104:15
lerna sill     at processTicksAndRejections (internal/process/task_queues.js:97:5)
lerna sill  HttpErrorGeneral: 403 Forbidden - PUT https://*********.jfrog.io/artifactory/api/npm/npm/@tl-prisma%2ftheme - forbidden
lerna sill     at /home/********/*********-prisma/node_modules/@evocateur/npm-registry-fetch/check-response.js:104:15
lerna sill     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
lerna sill   headers: [Object: null prototype] {
lerna sill     date: [ 'Tue, 04 Jan 2022 12:54:33 GMT' ],
lerna sill     'content-type': [ 'application/json' ],
lerna sill     'transfer-encoding': [ 'chunked' ],
lerna sill     connection: [ 'keep-alive' ],
lerna sill     'x-jfrog-version': [ 'Artifactory/7.26.3 72603900' ],
lerna sill     'x-artifactory-id': [ 'ae3bb8158f243e893763434e8d8327efd5d80bb0' ],
lerna sill     'x-artifactory-node-id': [ '*********-artifactory-primary-1' ],
lerna sill     'strict-transport-security': [ 'max-age=15724800; includeSubDomains' ],
lerna sill     'x-fetch-attempts': [ '1' ]
lerna sill   },
lerna sill   statusCode: 403,
lerna sill   code: 'E403',
lerna sill   method: 'PUT',
lerna sill   uri: 'https://*********.jfrog.io/artifactory/api/npm/npm/@tl-prisma%2ftheme',
lerna sill   body: {
lerna sill     error: 'forbidden',
lerna sill     reason: 'cannot modify pre-existing version: 1.1.1-beta-test.0.'
lerna sill   },
lerna sill   pkgid: '@tl-prisma/theme@1.1.1-beta-test.0'
lerna sill }
lerna ERR! E403 forbidden

    at ChildProcess.<anonymous> (/home/********/*********-prisma/node_modules/@auto-it/core/src/utils/exec-promise.ts:76:23)
    at ChildProcess.emit (events.js:314:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)Error: 
    at Object.execPromise (/home/********/*********-prisma/node_modules/@auto-it/core/src/utils/exec-promise.ts:17:20)
    at /home/********/*********-prisma/node_modules/@auto-it/npm/src/index.ts:1270:17
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by edouard-lopez** [comment]
Got the same issue directly with `lerna`

**Comment by hipstersmoothie** [comment]
It would seem the version has already been published. Can you provide more information about how you use auto? `auto info` and your authrc would help
