### ISSUE TITLE
"npx auto info" failing with "Failed to compile TypeScript: Debug Failure"  using auto.config.ts file 

### ISSUE THREAD

**Issue by danawoodman** [intuit/auto#2248]
**Describe the bug**

Getting the following error when running `npx auto info`:

`Failed to compile TypeScript: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature`

**To Reproduce**

Setup auto in an existing project via the instructions in the docs, then create a TypeScript config file:

`auto.config.ts`:

```typescript
import { AutoRc } from "auto";

export default function rc(): AutoRc {
	return {};
}
```

**Expected behavior**

Should output info about auto

**Screenshots**

**Environment information:**

Can't since `info` fails, but using auto 10.37.4, node v17.9.1, npm 8.11.0

**Additional context**

Full stack trace:

```
TypeScriptCompileError: Failed to compile TypeScript: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
    at Function.TypeScriptCompileError.fromError (/path/to/my/repo/node_modules/@endemolshinegroup/cosmiconfig-typescript-loader/src/Errors/TypeScriptCompileError.ts:20:12)
    at /path/to/my/repo/node_modules/@endemolshinegroup/cosmiconfig-typescript-loader/src/index.ts:14:34
    at Generator.next (<anonymous>)
    at /path/to/my/repo/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/path/to/my/repo/node_modules/tslib/tslib.js:114:16)
    at loader (/path/to/my/repo/node_modules/@endemolshinegroup/cosmiconfig-typescript-loader/src/index.ts:6:51)
    at Explorer.loadFileContent (/path/to/my/repo/node_modules/cosmiconfig/src/Explorer.ts:81:32)
    at Explorer.createCosmiconfigResult (/path/to/my/repo/node_modules/cosmiconfig/src/Explorer.ts:89:36)
    at Explorer.loadSearchPlace (/path/to/my/repo/node_modules/cosmiconfig/src/Explorer.ts:65:31)

```

**Comment by SeanKeenan-at** [comment]
Apparently [upgrading ts-node will fix this issue](https://github.com/intuit/auto/issues/2242).

**Comment by domoritz** [comment]
Well, I hoped it would fix the issue but I ams till getting the same build failure in https://github.com/vega/ts-json-schema-generator/actions/runs/3048721411/jobs/4914094811. This is till a bug, I think.

**Comment by hydrosquall** [comment]
I think the issue is that a dependency of `@auto-it/core` is using an old (2+) version of this library which can't go above version `9.x` . 

https://github.com/intuit/auto/blob/1bf25a53712d8b4458d7a63be4b2322538918c4d/packages/core/package.json#L41

If we were to upgrade the loader to https://github.com/Codex-/cosmiconfig-typescript-loader (which sets ts-node as a [peer](https://github.com/Codex-/cosmiconfig-typescript-loader/blob/fd8ef5812f81da2ff65dfce704e4a27b6ad5afb0/package.json#L39) instead of [direct dependency](https://github.com/EndemolShineGroup/cosmiconfig-typescript-loader/blob/b8b671bf3b86b43af0e8559af62c38010b8061f8/package.json#L44) )

The other workaround we're trying in the meantime is to use a JSON file instead of a TS file for configuring auto so that the the old loader code doesn't need to run at all. https://github.com/vega/ts-json-schema-generator/pull/1413

**Comment by domoritz** [comment]
Looks like there even is a pull request: https://github.com/EndemolShineGroup/cosmiconfig-typescript-loader/pull/215 but no updates. Maybe auto needs to use a different library that is more maintained.

**Comment by MikeMatusz** [comment]
Also had to stop using the TS config due to this, which is a shame since having typings available was really nice.  Looks like that library was archived October 2, 2022.  The cosmiconfig README recommends a fork of that as a replacement: https://github.com/codex-/cosmiconfig-typescript-loader

**Comment by hipstersmoothie** [comment]
Would you be interested In upgrading that for us?

**Comment by MikeMatusz** [comment]
Yeah, looks like a pretty straightforward replacement.  I think I can find some time in the next week or so to get a PR up.
