### ISSUE TITLE
Error: Working directory is not clean, make sure all files are committed

### ISSUE THREAD

**Issue by abhishekdhabriya** [intuit/auto#2402]
In Jenkins auto fails to create a release.  
It's running in a CI pipeline, so there shouldn't be an issue with the files being modified. 
10:57:00  lerna success found 2 packages
10:57:00  
10:57:04  ℹ  info      Adding "amalik4"'s contributions...
10:57:04  ℹ  info      Adding "cweller"'s contributions...
10:57:04  ✔  success   Updated contributors!
10:57:09  ℹ  info      Adding "cweller"'s contributions...
10:57:09  ✔  success   Updated contributors!
10:57:09  ✖  error     Changed Files:
10:57:09   M .npmrc
10:57:09  Error: Working directory is not clean, make sure all files are committed
10:57:09      at Auto.checkClean (/home/jenkins/agent/workspace/abric_genux-chat_genux-chat_main/node_modules/@auto-it/core/src/auto.ts:2091:11)
10:57:09      at runMicrotasks (<anonymous>)
10:57:09      at processTicksAndRejections (internal/process/task_queues.js:95:5)
10:57:09      at async Auto.publishFullRelease (/home/jenkins/agent/workspace/abric_genux-chat_genux-chat_main/node_modules/@auto-it/core/src/auto.ts:1774:7)
10:57:09      at async Auto.shipit (/home/jenkins/agent/workspace/abric_genux-chat_genux-chat_main/node_modules/@auto-it/core/src/auto.ts:1650:21)
10:57:09      at async execute (/home/jenkins/agent/workspace/abric_genux-chat_genux-chat_main/node_modules/auto/src/run.ts:88:9)
10:57:09      at async Object.runCli (/home/jenkins/agent/workspace/abric_genux-chat_genux-chat_main/node_modules/auto/src/run.ts:146:3)

**Comment by ykhandelwal913** [comment]
As per the report seems like .npmrc is being modified during the CI execution. Are you putting any content on the fly during execution? Please check if you can add this in .gitignore
